# Generated by Django 3.2.9 on 2021-11-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_plus_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plus',
            old_name='sno',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='plus',
            name='content',
        ),
        migrations.RemoveField(
            model_name='plus',
            name='name',
        ),
        migrations.RemoveField(
            model_name='plus',
            name='title',
        ),
        migrations.AddField(
            model_name='plus',
            name='file',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='plus',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
